#!/usr/bin/env bash
# shellcheck disable=SC2155
set -euo pipefail

readonly brew="/opt/homebrew/bin/brew"
readonly blueutil="/opt/homebrew/bin/blueutil"
readonly notificationTitle="Bluetooth connection"

readonly keyboard="08:95:42:E9:24:5C"
readonly trackpad="08:65:18:B8:EC:CD"

# Display notification
function notify() {
  local body="$1"
  osascript -e "display notification \"${body}\" with title \"${notificationTitle}\""
}

# Check if device is paired
function is_paired() {
  local macAddr="$1"
  "$blueutil" --paired | grep -iq "${macAddr//:/-}"
}

# Check if device is connected
function is_connected() {
  local macAddr="$1"
  local connected

  if ! connected="$("$blueutil" --is-connected "$macAddr" 2>/dev/null)"; then
    return 1
  elif [ "$connected" -ne 1 ]; then
    return 1
  else
    return 0
  fi
}

function connect() {
  local macAddr="$1"

  # Early return if device is already connected
  if is_connected "$macAddr"; then
    echo "✅"
    return 0
  fi

  # Unpair device first to enforce reconnection
  if is_paired "$macAddr"; then
    "$blueutil" --unpair "$macAddr" 2>/dev/null || true
    sleep 2
  fi

  # Reconnect device
  "$blueutil" --connect "$macAddr" 2>/dev/null || true
  "$blueutil" --wait-connect "$macAddr" 5 2>/dev/null || true

  if is_connected "$macAddr"; then
    echo "✅"
  else
    echo "❌"
  fi
}

# Prompt user to install blueutil with dialog
function show_install_dialog() {
  osascript <<APPLESCRIPT
set result to display alert "${notificationTitle}" ¬
  message "\"blueutil\" must be installed to automate Bluetooth connections. Install now?" ¬
  as critical ¬
  buttons {"Close", "Install"} ¬
  default button "Install" ¬
  cancel button "Close"
return button returned of result
APPLESCRIPT
}

# Verify that blueutil is installed
if [ ! -f "$blueutil" ]; then
  choice="$(show_install_dialog 2>/dev/null || true)"

  if [ "$choice" != "Install" ]; then
    notify "❌ blueutil must be installed first."
    exit 1
  fi

  notify "⏳ blueutil is being installed…"
  "$brew" install blueutil || (notify "❌ blueutil could not be installed."; exit 1)
  notify "✅ blueutil successfully installed."
fi

# Turn Bluetooth on
"$blueutil" --power 1

# Connect keyboard and trackpad
if is_connected "$keyboard" && is_connected "$trackpad"; then
  notify "✅ Connection is already established."
else
  notify "⏳ Connection is being established…"
  notify "$(connect "$keyboard") Magic Keyboard ∙ $(connect "$trackpad") Magic Trackpad"
fi
