#!/usr/bin/env sh
set -e

VERSION="$1"

# Resolve version from user input
case $VERSION in
  patch|p|next|n|minor|min|major|maj):
    VERSION="$(git next-version "$VERSION")"
    ;;
  "")
    echo "No release version set."
    exit 1
esac

# Lookup default branch
DEFAULT_BRANCH="$(git remote show origin | grep "HEAD branch" | sed 's/.*: //')"

# Make sure branches are up to date
git checkout "$DEFAULT_BRANCH"
git pull
git checkout develop

# Create release
git flow release start "$VERSION"
git flow finish

# Push branches
git push --atomic origin develop "$DEFAULT_BRANCH"
