#!/usr/bin/env sh
set -e

RED="\033[0;31m"
CYAN="\033[1;36m"
NC="\033[0m"

readonly phpVersion="$1"
readonly packageName="php@${phpVersion}"

if [ -z "$phpVersion" ]; then
    >&2 echo "${RED}No PHP version specified.${NC}"
    >&2 echo "Usage:"
    >&2 echo "  ${CYAN}$0 <php-version>${NC}"
    exit 1
fi

if ! ls "$(brew --cellar)/${packageName}" >/dev/null 2>&1 && ! brew --prefix --installed "$packageName" >/dev/null 2>&1; then
  >&2 echo "${RED}This PHP version is not supported."
  >&2 echo "${NC}Run ${CYAN}brew install ${packageName}${NC} to install it."
  exit 1
fi

brew unlink --quiet php "$packageName"
brew link --quiet --force --overwrite "$packageName"
echo
php -v
