#!/usr/bin/env sh
# shellcheck disable=SC2059
set -e

RED="\033[0;31m"
CYAN="\033[1;36m"
NC="\033[0m"

phpVersion="$1"
lastVersionFile="$HOME/.cache/switch-php/LAST_VERSION"

# Fail if PHP version is not specified
if [ -z "$phpVersion" ]; then
  echo "${RED}No PHP version specified.${NC}"
  echo "Usage:"
  echo "  ${CYAN}$0 <php-version>${NC}"
  exit 1
fi

# Try to switch back to last active PHP version, if requested and available
if [ "$phpVersion" = "-" ]; then
  if [ ! -f "$lastVersionFile" ]; then
    echo "${RED}No last active PHP version detected; please specify a concrete version instead.${NC}"
    echo "Usage:"
    echo "  ${CYAN}$0 <php-version>${NC}"
    exit 1
  fi

  phpVersion="$(cat "$lastVersionFile")"
fi

readonly phpPackage="php@${phpVersion}"
readonly pcovPackage="pcov@${phpVersion}"
readonly xdebugPackage="xdebug@${phpVersion}"

_populate_current_version() {
  currentVersion="$(php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;' 2>/dev/null || true)"

  if [ ! -f "$lastVersionFile" ]; then
    mkdir -p "$(dirname "$lastVersionFile")"
  fi

  if [ -n "$currentVersion" ]; then
    echo "$currentVersion" > "$lastVersionFile"
  fi
}

_activate() {
  brew unlink --quiet php "$phpPackage"
  brew link --quiet --force --overwrite "$phpPackage"
  echo
  php -v
  xd status
}

_install() {
  brew tap shivammathur/php
  brew install "shivammathur/php/${phpPackage}"
  brew tap shivammathur/extensions
  brew install "shivammathur/extensions/${pcovPackage}"
  brew install "shivammathur/extensions/${xdebugPackage}"

  _activate
  _write_config

  php --ini
}

_write_config() {
  configDir="$(php --ini 2>/dev/null | awk -F: '/Scan for additional .ini files/{gsub(/^[ \t]+/, "", $2); print $2}' | tr -d \")"

  echo "memory_limit=2G" > "${configDir}/99-memory-limit.ini"

  # Disable xdebug by default
  mv "${configDir}/20-xdebug.ini" "${configDir}/20-xdebug.ini.disabled" >/dev/null 2>&1 || true
}

_populate_current_version

if ls "$(brew --cellar)/${phpPackage}" >/dev/null 2>&1 || brew --prefix --installed "$phpPackage" >/dev/null 2>&1; then
  _activate
else
  echo "${RED}This PHP version is not installed.${NC}"
  printf "Install now? [${CYAN}Y${NC}/n] "
  read -r install

  case "$install" in
    Y*|y*|'') _install;;
    *) echo "${CYAN}Aborted.${NC}"; exit 1;;
  esac
fi
